export  { default as Navbar  } from './Navbar/Navbar'
export  { default as Products  } from './Products/Products'
export  { default as Cart  } from './Cart/Cart'
export  { default as About  } from './About/About'
export  { default as Footer  } from './Footer/Footer'
export  { default as LoginAndRegister  } from './Auth/Auth'