export { default as Navbar } from "./Navbar/Navbar";
export { default as Products } from "./Products/Products";
export { default as Category } from "./Admin/Category/Category";
export { default as ProductById } from "./Products/ProductById";
export { default as ManageProducts } from "./Admin/adminProduct/ManageProduct";
export { default as Cart } from "./Cart/Cart";
export { default as Admin } from './Admin/Admin'
export { default as About } from "./About/About";
export { default as Footer } from "./Footer/Footer";
export { default as LoginAndRegister } from "./Auth/Auth";
