export  { default as Navbar  } from './Navbar'
export  { default as Products  } from './Products/Products'
export  { default as Cart  } from './Cart/Cart'
export  { default as About  } from './About/About'
export  { default as LoginAndRegister  } from './Auth/Auth'